--- #YAML:1.0
name:                Catalyst-Plugin-CommandLine
version:             0.03
abstract:            Catalyst plugin to make  available also for scripts.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Catalyst::Request:             0
    Catalyst::Response:            0
    Class::Data::Inheritable:      0
    English:                       0
    HTTP::Headers:                 0
    NEXT:                          0
    Test::More:                    0
    UNIVERSAL:                     0
    URI::http:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jozef Kutej <jozef@kutej.net>
